ADDRESS = "127.0.0.1"
SERVER_PORT = 5600
CLIENT_PORT = 8000
SERVER_ID = 1111

MESSAGE_END_SESSION = "END_SESSION"
MESSAGE_START_TRAINING = "START_TRAINING"
MESSAGE_TRAINING_COMPLETED = "TRAINING_COMPLETED"
MESSAGE_START_SECRET_SHARING = "START_SECRET_SHARING"
MESSAGE_FL_UPDATE = "FL_UPDATE"
MESSAGE_MODEL_SHARE = "MODEL_SHARE"
MESSAGE_SHARING_COMPLETE = "SHARING_COMPLETE"
MESSAGE_START_ASSEMBLY = "START_ASSEMBLY"

CHUNK_SIZE = 400
BIT_SIZE = 4096

NODES = 5
ROUNDS = 3
EPOCHS = 2
GROUPINGS = 3
DATASET = 'mnist'
DATASETS = ['cifar-10', 'f-mnist', 'mnist', 'svhn']
